### ISSUE TITLE
Error: Unexpected token (Note that you need plugins to import files...

### ISSUE THREAD

**Issue by munrocket** [surma/rollup-plugin-assemblyscript#1]
Hello! Thank you for the great library!

Here my feedback:
* Current documentation without proper examples (I am searched existed code in the wild)
* I am getting an error

Error:
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
wasm/mandel.as (1:5)
1: type float = f64;
        ^
2: type int = i32;
3: let LO: float = 0.;
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/munrocket/code/double.js/node_modules/rollup/dist/shared/rollup.js:10116:30)
    at Module.error (/home/munrocket/code/double.js/node_modules/rollup/dist/shared/rollup.js:14550:16)
    at tryParse (/home/munrocket/code/double.js/node_modules/rollup/dist/shared/rollup.js:14443:23)
    at Module.setSource (/home/munrocket/code/double.js/node_modules/rollup/dist/shared/rollup.js:14832:33)
    at /home/munrocket/code/double.js/node_modules/rollup/dist/shared/rollup.js:16692:20
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async rollupInternal (/home/munrocket/code/double.js/node_modules/rollup/dist/shared/rollup.js:18088:18)
    at async execute (/home/munrocket/code/double.js/node_modules/rollup/dist/bin/rollup:1532:17)
```

File structure:
```
├──rollup.config.js
├──wasm
|   ├── mandel.as
|   └── mandel.wasm
```

Rollup config:
```js
import { asc } from "rollup-plugin-assemblyscript";

//...

export default [
  {
    input: 'wasm/mandel.as',
    //output: { dir: 'wasm' },
    plugins: [
      asc({
        compilerOptions: {
          //outFile: 'wasm/mandel.wasm',
          optimizeLevel: 3,
          shrinkLevel: 2,
          runtime: 'none',
          importMemory: true
        }
      })
    ]
  }
];
```
I took part of the config in your package: [letterboxer](https://github.com/surma/letterboxer/blob/master/rollup.config.js)
Here my repo where I am tried: [double.js](https://github.com/munrocket/double.js)

Sorry, probably I miss something and I need additional rollup plugin for files.

**Comment by munrocket** [comment]
Seems .as not supported.
